# Generated by Django 4.0.5 on 2022-06-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('shortName', models.CharField(max_length=20)),
                ('decsription', models.TextField(blank=True)),
                ('icon', models.ImageField(upload_to='', verbose_name='images/currency/')),
            ],
        ),
    ]
