# Generated by Django 4.0.5 on 2022-07-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='shortName',
            new_name='shortname',
        ),
    ]
