# Generated by Django 4.0.5 on 2022-07-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rename_shortname_cryptocurrency_shortname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrency',
            old_name='decsription',
            new_name='description',
        ),
    ]
