# Generated by Django 4.0.5 on 2022-07-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_rename_decsription_cryptocurrency_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='iconpath',
            field=models.CharField(default='default path', max_length=96),
            preserve_default=False,
        ),
    ]
