# Generated by Django 4.0.5 on 2022-07-04 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_alter_cryptocurrency_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=96, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='currency.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/currency/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='iconpath',
            field=models.CharField(max_length=96, verbose_name='Путь к иконке'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='shortname',
            field=models.CharField(max_length=20, verbose_name='Краткое название'),
        ),
    ]
