# Generated by Django 4.0.5 on 2022-07-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='iconpath',
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='currency/images/', verbose_name='Иконка'),
        ),
    ]
